#!/usr/bin/env python3
"""Build pkb/TOOL_PRAATGEN_LINT.zip: one file, TOOL_PRAATGEN_LINT.txt, which is
tools/praatgen_lint.py plus an index of the PKB command references, so the
linter runs from one project file. It ships zipped because the Claude app
returns at most 256 KiB of a text project file, while a zip is saved whole.

Run from the repo root after any change to the linter, a COMMANDS_*.txt file,
the catalogue, APPENDIX_B, a RULES file or an eml-*.txt library file:
    python3 tools/build_lint.py
Run with --check to confirm the PKB copy matches the current sources.
"""
import importlib.util
import io
import json
import sys
import zipfile

SRC = 'tools/praatgen_lint.py'
OUT = 'pkb/TOOL_PRAATGEN_LINT.zip'
NAME = 'TOOL_PRAATGEN_LINT.txt'
MARKER = 'EMBEDDED_INDEX = None'
HEADER = ('# TOOL_PRAATGEN_LINT.txt is a Python 3 script.\n'
          '# Part of EML PraatGen GPL-3.0-or-later - Ian Howell, Embodied Music Lab\n'
          '# Run:  python3 TOOL_PRAATGEN_LINT.txt SCRIPT.praat [PLAN.md]\n'
          '# Generated by tools/build_lint.py from tools/praatgen_lint.py\n'
          '# and the PKB COMMANDS_*.txt files, the two catalogue parts,\n'
          '# APPENDIX_B_FUNCTIONS.txt, the RULES files and the eml-*.txt library.\n'
          '# Do not edit; regenerate.\n')


def build():
    spec = importlib.util.spec_from_file_location('lint', SRC)
    lint = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(lint)
    index = {'curated': {k: [list(e) for e in v]
                         for k, v in sorted(lint.load_curated('pkb').items())},
             'catalogue': {k: [list(e) for e in v]
                           for k, v in sorted(lint.load_catalogue('pkb').items())},
             'functions': sorted(lint.load_functions('pkb').items()),
             'tokens': lint.load_token_hashes('pkb'),
             'procedures': lint.load_procedures('pkb')}
    src = open(SRC, encoding='utf-8').read()
    assert src.count(MARKER) == 1
    # One entry per line, so no line is too long for a reader to show whole.
    lit = 'EMBEDDED_INDEX = ' + json.dumps(index, indent=0, separators=(',', ':'),
                                           ensure_ascii=True)
    body = src.replace('#!/usr/bin/env python3\n', '', 1)
    body = body.replace(MARKER + '  # replaced in the PKB copy by tools/build_lint.py', lit)
    assert MARKER not in body
    return HEADER + body


def pack(text):
    """Zip the linter with a fixed timestamp, so the same text gives the same bytes."""
    info = zipfile.ZipInfo(NAME, date_time=(2026, 1, 1, 0, 0, 0))
    info.compress_type = zipfile.ZIP_DEFLATED
    info.external_attr = 0o644 << 16
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, 'w') as z:
        z.writestr(info, text.encode('utf-8'))
    return buf.getvalue()


if __name__ == '__main__':
    data = pack(build())
    if '--check' in sys.argv:
        try:
            ok = open(OUT, 'rb').read() == data
        except FileNotFoundError:
            ok = False
        print('PKB linter is current' if ok else 'PKB linter is STALE: regenerate')
        sys.exit(0 if ok else 1)
    open(OUT, 'wb').write(data)
    print(f'wrote {OUT} ({len(data)} bytes)')
